// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package jobs

import (
	"github.com/pwestlake/equity-fund/commons/pkg/dao"
	service2 "github.com/pwestlake/equity-fund/commons/pkg/service"
	"github.com/pwestlake/equity-fund/eodupdatejob/pkg/service"
)

// Injectors from wire.go:

func InitializeBackFillJob() BackFillJob {
	marketStackService := service.NewMarketStackService()
	yahooService := service.NewYahooService()
	lseService := service.NewLSEService()
	equityCatalogItemDAO := dao.NewEquityCatalogItemDAO()
	equityCatalogService := service2.NewEquityCatalogService(equityCatalogItemDAO)
	endOfDayItemDAO := dao.NewEndOfDayItemDAO()
	endOfDayService := service2.NewEndOfDayService(endOfDayItemDAO)
	newsItemDAO := dao.NewNewsItemDAO()
	newsService := service2.NewNewsService(newsItemDAO)
	nlpService := service.NewNLPService()
	backFillJob := NewBackFillJob(marketStackService, yahooService, lseService, equityCatalogService, endOfDayService, newsService, nlpService)
	return backFillJob
}
